In [2]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [13]:
df.describe()

,customer_id,age,purchase_amount_(usd),review_rating,previous_purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [15]:
df['review_rating']=df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [21]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [9]:
# create age group
labels=['18–25','26–40','41–60','61+']
df['age_group']=pd.qcut(df['Age'],q=4,labels=labels)
df[['Age','age_group']].head(10)

   Age age_group
0   55     41–60
1   19     18–25
2   50     41–60
3   21     18–25
4   45     41–60
5   46     41–60
6   63       61+
7   27     18–25
8   26     18–25
9   57     41–60

   Age age_group
0   55     41–60
1   19     18–25
2   50     41–60
3   21     18–25
4   45     41–60
5   46     41–60
6   63       61+
7   27     18–25
8   26     18–25
9   57     41–60

In [32]:
#create column purchase_frequency_days

frequency_mapping={
    'Fortnightly': 14.0,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-weekly':14,
    'Annually':365,
    'Every 3 Months':90
        }
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [33]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [34]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [35]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [36]:
df=df.drop('promo_code_used', axis=1)

In [37]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [39]:
pip install mysql-connector-python sqlalchemy ipython-sql

Requirement already satisfied: mysql-connector-python in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.0.54)
Requirement already satisfied: ipython-sql in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.5.0)
Requirement already satisfied: greenlet>=1 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: prettytable in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython-sql) (3.18.0)
Requirement already satisfied: ipython in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython-sql) (9.14.0)
Requirement already satisfied: sqlparse in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython-sql) (0.6.0)
Requirement already satisfied: six in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: psutil>=7 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython->ipython-sql) (5.15.1)
Requirement already satisfied: wcwidth in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jedi>=0.18.2->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\archa\AppData\Local\Programs\Python\Python312\Lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
# 1. Load the SQL extension
%load_ext sql
import urllib.parse

# 2. Define connection parameters
USER = "root"
PASSWORD = urllib.parse.quote_plus("Archana@123") 
HOST = "127.0.0.1"        # or your server IP address
DATABASE = "customer_behaviour"

# 3. Create the connection string (Using mysql-connector backend)
connection_string = f"mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}/{DATABASE}"

# 4. Connect to the database
%sql $connection_string

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [11]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

# 1. Read your data file
file_path = "customer_shopping_behavior.csv"
df = pd.read_csv(file_path)

# 2. Clean up the columns so they are clean database identifiers
df.columns = df.columns.str.strip().str.lower()
df.columns = df.columns.str.replace(' ', '_').str.replace('/', '_').str.replace('(', '').str.replace(')', '')

# 3. Connection variables
USER = "root"
PASSWORD = urllib.parse.quote_plus("Archana@123")
HOST = "127.0.0.1"
DATABASE = "customer_behaviour"



# 4. Initialize MySQL engine connection
engine = create_engine(f"mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}/{DATABASE}")

# 5. Load data into the 'customer' table
# Set if_exists='append' if the table already exists and you want to add rows
# Set if_exists='replace' if you want to drop the old structure and create it brand new
df.to_sql('customer', con=engine, if_exists='replace', index=False)

print("Data successfully mapped and loaded into the 'customer' table!")

Data successfully mapped and loaded into the 'customer' table!

In [15]:
# create age group

import pandas as pd
import urllib.parse
df=pd.read_csv('customer_shopping_behavior.csv')
# create age group
labels=['18–25','26–40','41–60','61+']
df['age_group']=pd.qcut(df['Age'],q=4,labels=labels)
from sqlalchemy import create_engine


# 2. TRANSFORM FIELD NAMES: Convert all columns to lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})



# 2. Define the name of your new Excel file
excel_filename = 'customer_shopping_behavior.xlsx'

# 3. Export the DataFrame to an Excel file
df.to_excel(excel_filename, index=False, sheet_name='customer_shopping_behavior')

# 4. Print confirmation (Fixed variable name inside the brackets here)
print(f"Data successfully saved to Excel file: {excel_filename}")



# 2. Connect to a local SQLite database (it will create the file if it doesn't exist)
# 3. Connection variables
USER = "root"
PASSWORD = urllib.parse.quote_plus("Archana@123")
HOST = "127.0.0.1"
DATABASE = "customer_behaviour"

# 4. Initialize MySQL engine connection
engine = create_engine(f"mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}/{DATABASE}")

# 5. Load data into the 'customer' table
# Set if_exists='append' if the table already exists and you want to add rows
# Set if_exists='replace' if you want to drop the old structure and create it brand new
df.to_sql('customer', con=engine, if_exists='replace', index=False)

print("Data successfully mapped and loaded into the 'customer' table!")

Data successfully saved to Excel file: customer_shopping_behavior.xlsx
Data successfully mapped and loaded into the 'customer' table!